// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PiecOfArt_Project;

#nullable disable

namespace PiecOfArt_Project.Migrations
{
    [DbContext(typeof(AppDbContextt))]
    [Migration("20250326113312_ss")]
    partial class ss
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PiecOfArt_Project.Models.ArtPiece", b =>
                {
                    b.Property<int>("ArtPieceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtPieceId"));

                    b.Property<string>("ArtPieceDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArtPieceTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("LoyaltyCardId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ArtPieceId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LoyaltyCardId");

                    b.ToTable("ArtPieces");
                });

            modelBuilder.Entity("PiecOfArt_Project.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("PiecOfArt_Project.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("PiecOfArt_Project.Models.LoyaltyCard", b =>
                {
                    b.Property<int>("LoyaltyCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoyaltyCardId"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.HasKey("LoyaltyCardId");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("LoyaltyCards");
                });

            modelBuilder.Entity("PiecOfArt_Project.Models.ArtPiece", b =>
                {
                    b.HasOne("PiecOfArt_Project.Models.Category", "Category")
                        .WithMany("PieceOfArts")
                        .HasForeignKey("CategoryId");

                    b.HasOne("PiecOfArt_Project.Models.Customer", "Customer")
                        .WithMany("ArtPieces")
                        .HasForeignKey("CustomerId");

                    b.HasOne("PiecOfArt_Project.Models.LoyaltyCard", null)
                        .WithMany("ArtPieces")
                        .HasForeignKey("LoyaltyCardId");

                    b.Navigation("Category");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PiecOfArt_Project.Models.LoyaltyCard", b =>
                {
                    b.HasOne("PiecOfArt_Project.Models.Customer", "Customer")
                        .WithOne("LoyaltyCard")
                        .HasForeignKey("PiecOfArt_Project.Models.LoyaltyCard", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("PiecOfArt_Project.Models.Category", b =>
                {
                    b.Navigation("PieceOfArts");
                });

            modelBuilder.Entity("PiecOfArt_Project.Models.Customer", b =>
                {
                    b.Navigation("ArtPieces");

                    b.Navigation("LoyaltyCard");
                });

            modelBuilder.Entity("PiecOfArt_Project.Models.LoyaltyCard", b =>
                {
                    b.Navigation("ArtPieces");
                });
#pragma warning restore 612, 618
        }
    }
}
